scrape_configs:
  - job_name: 'qpacs2'
    scrape_interval: 10s
    metrics_path: /orthanc/tools/metrics-prometheus
    basic_auth:
      username: serve
      password: serveritegno
    static_configs:
      - targets: ['192.168.30.59:8443']

