global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
   - job_name: 'orthanc'
     scrape_interval: 10s
     metrics_path: /tools/metrics-prometheus
     static_configs:
       - targets: ['orthanc:8042']
     basic_auth:
      username: serve
      password: serveritegno
   - job_name:  'cadvisor/node-exporter'
     scrape_interval:     5s # By default, scrape targets every 15 seconds.
     static_configs:
      - targets: ['cadvisor:8080','node-exporter:9100']
 